### ISSUE TITLE
Run github CI builds and tests also on Pull Request

### ISSUE THREAD

**Issue by ivalery111** [libnet/libnet#147]
I noticed that github CI builds and tests does not running on Pull Requests.

I think the solution is add `pull_request` to the `build.yml` and `build-freebsd.yml`:
```
on:
  push:
    branches:
      - '*'
    pull_request:
      - '*'
```

OR in more short variant:
```
on: [push, pull_request]
```
